### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by paulheising** [cmuench/ulauncher-todoist#10]
I have been using the todoist extension for ULauncher for a long time, but recently, it just stopped working. When I try to add a task via the extension and commit it, nothing happens. I don't get the notification popping up that I used to know, neither is the new task created in my todoist inbox.

I tried updating the extension and creating a new API Key in todoist and adding it to the extension configuration, but unfortunately it didn't help

**Comment by paulheising** [comment]
Maybe the used API is not supported any more? I see this in the terminal, when running `ulauncher -v` and entering `todo create asdfg`:

```
 https://api.todoist.com:443 "GET /sync/v8/add_item?token=this_is_my_token&content=asdfg HTTP/1.1" 410 None
```

**Comment by cmuench** [comment]
@paulheising Thanks. Can confirm that. It's currently broken.

I see this stacktrace on my machine:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3.10/site-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/cmuench/Workspaces/opensource/ulauncher/ulauncher-todoist/todoistext/ItemEnterEventListener.py", line 25, in on_event
    extension.create_task(data["task"], data["project_id"])
  File "/home/cmuench/Workspaces/opensource/ulauncher/ulauncher-todoist/todoistext/TodoistExtension.py", line 49, in create_task
    self.show_notification(f"Task {new_item['id']} created", make_sound=True)
TypeError: string indices must be integers
```

Looks like a small int cast issue. I will try to fix it.

**Comment by cmuench** [comment]
Seems that we have to replace the API,
See: https://developer.todoist.com/rest/v2/?python#overview

**Comment by cmuench** [comment]
@paulheising I pushed a fix.
Please install the new api package on your machine.

`pip install todoist-api-python`

**Comment by cmuench** [comment]
Unser that there is something broken in the way the tasks are created. I will try to fix that tomorrow.

**Comment by cmuench** [comment]
@paulheising Task creation is fixed.

**Comment by paulheising** [comment]
@cmuench Thanks for looking into it. I just updated the extension and did the `pip install todoist-api-python`, but I still can't create tasks via uLauncher.

Log output, obtained via `ulauncher -v`:

```
2023-01-09 16:12:04,410 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event ItemEnterEvent to "com.github.cmuench.ulauncher-todoist"
com.github.cmuench.ulauncher-todoist | 2023-01-09 16:12:04,464 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event ItemEnterEvent
com.github.cmuench.ulauncher-todoist | 2023-01-09 16:12:04,465 | DEBUG | todoistext.ItemEnterEventListener: on_event() | {'action': 'create', 'content': 'Test', 'project_id': None}
com.github.cmuench.ulauncher-todoist | 2023-01-09 16:12:04,466 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): api.todoist.com:443
com.github.cmuench.ulauncher-todoist | 2023-01-09 16:12:04,604 | DEBUG | urllib3.connectionpool: _make_request() | https://api.todoist.com:443 "POST /sync/v8/quick/add HTTP/1.1" 410 None
```

The difference compared to before is, that now I don't get any error message any more. But we can see that the Todoist API still responds with a 410, which supports my former suspicion on the API being deprecated and gone.

But maybe I still missed the proper package versions. Could you point out how to check it / which version of the incorporated packages are required?

**Comment by paulheising** [comment]
Another hint: 

Before I followed your hint regarding `pip install todoist-api-python`, I followed the hint shown on the settings page of ulauncher:

![Screenshot_20230109_160951](https://user-images.githubusercontent.com/19818829/211342000-4245e031-18b5-4bab-a0c8-445e70d3df1f.png)

Maybe there are some conflicts regarding the different packages?

**Comment by cmuench** [comment]
> Another hint:
> 
> Before I followed your hint regarding `pip install todoist-api-python`, I followed the hint shown on the settings page of ulauncher:
> 
> ![Screenshot_20230109_160951](https://user-images.githubusercontent.com/19818829/211342000-4245e031-18b5-4bab-a0c8-445e70d3df1f.png)
> 
> Maybe there are some conflicts regarding the different packages?

I am not a Python expert but I tested with `pip install todoist-api-python` and `pip install todoist_api_python`. Seems that pip is normalizing the package name. It's at the end the same package.
The only difference I see from example is that `--user` is installing the dependency in your home directory.

**Comment by paulheising** [comment]
I'll need to take a further look at this during the next days. For now, it looks like I can only get the latest version of `todoist-api-python` (which is 2.0.2) when I install it via `pip3`. However, uLauncher / the Todoist Extension seems to not recognize that, as it would keep telling me to install that package. 

If I install it via `pip`, like you suggested, I would always get an older version (1.1.1). In this case, the extension does not crash immediately but it would not create any task (original issue of this thread).

I'm not a big python expert neither, not sure even why there is `pip` and `pip3`, but there seems to be some weird version differences around. I'll have a further look when I find time during the next days.

**Comment by cmuench** [comment]
@paulheising thanks for testing. If will try then to pin the version in the requirements.txt
Let's figure out if there is a difference between pip and pip3 on machines with only python3.

**Comment by cmuench** [comment]
https://stackoverflow.com/questions/40832533/pip-or-pip3-to-install-packages-for-python-3/40832677#40832677

**Comment by paulheising** [comment]
The deeper I dive into this, the more confused I get. Here are my current findings:

- I need the latest version of [todoist-api-python](https://pypi.org/project/todoist-api-python/), which seems to be 2.0.2
- When I try to install it normally via `pip` or `pip3`, I only get 1.1.1. 
- Using the `--verbose` parameter, I found out, that `todoist-api-python` requires Python >= 3.9
- I have python 3.8 install, so that explains why I won't get the latest version of todoist-api-python
- Upgrading to python >= 3.9 seems to be complicated though. I tried it using this guide: https://phoenixnap.com/kb/upgrade-python
- Using the guide, I was able to successfully get python to 3.9 or even 3.11 (tried) both up and running
- However, as soon as I switch the symlink as suggested in the guide, to a newer python version, some of my applications would not launch any more. This includes the terminal and also uLauncher
- So I still had to go back to python 3.8 in order to use my computer properly.
- The question is: How would you manage to get the latest version of todoist-api-python, while not breaking various applications from performing a python upgrade? Even more confusing: If uLauncher seems to require python 3.8 (won't launch otherwise), how is it even possible to have python >= 3.9 running at the same time in order to use the todoist-api-python package for the todoist extension

Could you check which versions of python and pip you got installed?

Mine: 

```
➜  ~ python3 --version                                                                   
Python 3.8.10
➜  ~ python2 --version
Python 2.7.18
➜  ~ pip --version                                                                       
pip 22.3.1 from /home/paul.heising/.local/lib/python3.8/site-packages/pip (python 3.8)
➜  ~ pip3 --version
pip 22.3.1 from /home/paul.heising/.local/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by paulheising** [comment]
I was able to install the latest version of todoist-api-python via `python3.9 -m pip install todoist-api-python`

But of course, uLauncher won't respect that, because this is not the default python version I have installed. So the plugin still does not work unfortunately

**Comment by cmuench** [comment]
> The deeper I dive into this, the more confused I get. Here are my current findings:
> 
> * I need the latest version of [todoist-api-python](https://pypi.org/project/todoist-api-python/), which seems to be 2.0.2
> * When I try to install it normally via `pip` or `pip3`, I only get 1.1.1.
> * Using the `--verbose` parameter, I found out, that `todoist-api-python` requires Python >= 3.9
> * I have python 3.8 install, so that explains why I won't get the latest version of todoist-api-python
> * Upgrading to python >= 3.9 seems to be complicated though. I tried it using this guide: https://phoenixnap.com/kb/upgrade-python
> * Using the guide, I was able to successfully get python to 3.9 or even 3.11 (tried) both up and running
> * However, as soon as I switch the symlink as suggested in the guide, to a newer python version, some of my applications would not launch any more. This includes the terminal and also uLauncher
> * So I still had to go back to python 3.8 in order to use my computer properly.
> * The question is: How would you manage to get the latest version of todoist-api-python, while not breaking various applications from performing a python upgrade? Even more confusing: If uLauncher seems to require python 3.8 (won't launch otherwise), how is it even possible to have python >= 3.9 running at the same time in order to use the todoist-api-python package for the todoist extension
> 
> Could you check which versions of python and pip you got installed?
> 
> Mine:
> 
> ```
> ➜  ~ python3 --version                                                                   
> Python 3.8.10
> ➜  ~ python2 --version
> Python 2.7.18
> ➜  ~ pip --version                                                                       
> pip 22.3.1 from /home/paul.heising/.local/lib/python3.8/site-packages/pip (python 3.8)
> ➜  ~ pip3 --version
> pip 22.3.1 from /home/paul.heising/.local/lib/python3.8/site-packages/pip (python 3.8)
> ```

ok. I will to figure out how we can get it running with python 3.8.

**Comment by cmuench** [comment]
@paulheising I checked the dependencies of the package.
The version 2.0.0 is compatible with Python 3.8.
I updated the requirements.txt file in the project,

I was able to downgrade the package.

Can you try this?
`pip install todoist-api-python==2.0.0`

**Comment by paulheising** [comment]
I can't

```
➜  ~ pip install todoist-api-python==2.0.0        
Defaulting to user installation because normal site-packages is not writeable
ERROR: Ignored the following versions that require a different python version: 2.0.0 Requires-Python >=3.9,<4.0; 2.0.1 Requires-Python >=3.9,<4.0; 2.0.2 Requires-Python >=3.9,<4.0
ERROR: Could not find a version that satisfies the requirement todoist-api-python==2.0.0 (from versions: 1.1.0, 1.1.1)
ERROR: No matching distribution found for todoist-api-python==2.0.0
```

**Comment by paulheising** [comment]
I strongly suppose you got it running on pyhton >= 3.9 somehow, but I have no idea how 😄

**Comment by cmuench** [comment]
@paulheising My mistake. 
1.x is for python 3.8
2.x is min python 3.9

The problem is that the 1.x version of the package is for the deprecated api.
So there there is no official todoist api for python 3.8 available. :-(
Means that I have to implement a lib by my own.

**Comment by paulheising** [comment]
Hold on, if you were able to get the whole plugin running with the new API, that maybe means I have some weird system setup. Maybe I have to upgrade to python >=3.9 in such a way that the existing apps won't break.

Can you confirm that you got python >= 3.9 installed and uLauncher still working? Because then I could try to figure out how to update it properly, and you would not have to reinvent the wheel.

**Comment by cmuench** [comment]
@paulheising I have Python 3.10.8 installed and ulauncher is working.

**Comment by cmuench** [comment]
The upcoming ulauncher v6 is tested with Python 3.9 and Python 3.11.

**Comment by paulheising** [comment]
Weird... that means there has to be a way to upgrade python without breaking existing applications... I will try to figure that out. For the part of the uLauncher Todoist Plugin, it seems to be sufficient to do what you did - upgrading the library to 2.x. So I think you've done your part and this issue can be closed imo.

Thank you so far 🙂

**Comment by cmuench** [comment]
@paulheising Thanks for reporting the issue.
